[general]
bios_path = "bios.bin"
bios_skip = false
save_folder = ""

[cartridge]
# Possible values: detect, none, sram, flash64, flash128, eeprom512, eeprom8192
save_type = "detect"
# Force-enable RTC emulation, otherwise rely on game database.
force_rtc = true
# Force-enable Solar Sensor emulation, otherwise rely on game database.
force_solar_sensor = false
# Solar Sensor light intensity (0 = lowest intensity, 255 = highest intensity)
solar_sensor_level = 23

[video]
filter = "linear"
color_correction = "agb"
lcd_ghosting = true

[audio]
# Possible values: cosine, cubic, sinc64, sinc128, sinc256
resampler = "cubic"
# Reimplementation of the popular MP2K/M4A audio mixer with higher quality.
# This is experimental and may still have issues.
mp2k_hle_enable = false
# Use cubic interpolation in the MP2K reimplementation.
mp2k_hle_cubic = true
# Force-enable the reverb effect
mp2k_hle_force_reverb = true

[input]
hold_fast_forward = true
fast_forward = [32, -1, -1, -1, 0]
controller_guid = ""
[input.gba]
a = [65,-1,-1,-1,0]
b = [83,-1,-1,-1,0]
select = [16777219,-1,-1,-1,0]
start = [16777220,-1,-1,-1,0]
right = [16777236,-1,-1,-1,0]
left = [16777234,-1,-1,-1,0]
up = [16777235,-1,-1,-1,0]
down = [16777237,-1,-1,-1,0]
l = [68,-1,-1,-1,0]
r = [70,-1,-1,-1,0]

[window]
fullscreen = false
fullscreen_show_menu = false
scale = 2
# Set to zero to unlock the scale
maximum_scale = 0
# Show the current frames per second in the window title
show_fps = false
# Lock the screen to a 3:2 aspect ratio
lock_aspect_ratio = true
# Snap screen size to integer multiples of the original screen width and height
use_integer_scaling = false
# Pause emulator when the main window becomes inactive
pause_emulator_when_inactive = true
